version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="mongo"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db